git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="OneHalfDark"
gui:
  commitlength:
    show: true
  # language: zh
  mouseevents: false
  scrollheight: 2
  scrollpastbottom: true
  theme:
    lightTheme: false
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - blue
